name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Pest Configuration
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
                   bootstrap="vendor/autoload.php"
                   colors="true"
          >
              <testsuites>
                  <testsuite name="Test Suite">
                      <directory suffix="Test.php">./tests</directory>
                  </testsuite>
              </testsuites>
              <coverage processUncoveredFiles="true">
                  <include>
                      <directory suffix=".php">./src</directory>
                  </include>
              </coverage>
          </phpunit>' > phpunit.xml

      - name: Execute tests via Pest
        run: vendor/bin/pest

      - name: Execute static analysis
        run: vendor/bin/phpstan analyse

      - name: Check coding style
        run: vendor/bin/pint --test
